services:
  - type: web
    name: task-manager-api
    env: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: task-manager-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: task-manager-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: task-manager-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: task-manager-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: task-manager-db
          property: password

databases:
  - name: task-manager-db
    plan: free
    region: oregon
