services:
  - type: web
    name: task-manager-api
    env: php
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://task-manager-api-6lr6.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: task-manager-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: task-manager-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: task-manager-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: task-manager-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: task-manager-db
          property: password

databases:
  - name: task-manager-db
    plan: free
